# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Notebook
description: > # this means to ignore newlines until "baseurl:"
  A minimalistic theme for Jekyll, based on hack.css
repository: https://github.com/wemake-services/jekyll-theme-hackcss
baseurl: /book  # the subpath of your site, e.g. /blog
url: https://aswincsekar.github.io  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: aswincsekar
email: aswincsekar@gmail.com

navigation:
  - text: Home
    url: /
  - text: Docs
    url: /docs
  - text: Updates
    url: /updates

projects:
  - name: VideoMag
    description: Eulerian Video Magnification for Revealing Subtle Changes
    link: https://github.com/aswincsekar/VideoMag
    image: http://www.newton.ac.uk/files/covers/968361.jpg

social:
  - service: github
    username: aswincsekar
    link: https://github.com/aswincsekar

# Plugins
gems:
  - jekyll-seo-tag
